### ISSUE TITLE
Enable Custom Safe Apps

### ISSUE THREAD

**Issue by davidsemakula** [protofire/moonbeam-safe-react#44]
First off, great work on the project :slightly_smiling_face:

# Context
I recently participated in the [Moonbeam Illuminate Hackathon](https://gitcoin.co/hackathon/illuminate) and built a [Safe App](https://github.com/davidsemakula/safe-hyperlane-router) for managing assets and interacting with dApps on multiple chains from one Safe account using [Hyperlane Interchain Accounts](https://docs.hyperlane.xyz/hyperlane-docs/developers/send).

It's an interesting project for me and one I'll likely continue to hack on beyond the hackathon but it currently can't be used with Moonbeam as the origin/controller chain because of this issue.

# Problem
This fork currently removes/disables the Safe Apps page completely. I think I understand the rationale for the decision since not a lot third party safe apps support moonbeam at the moment. However, this also removes the ability for the user to install custom safe apps.

# Request
Enable the Safe Apps page so that the user can at least have the option to install custom apps even if the full safe apps catalogue remains disabled.

# Proposal
I'm a fullstack developer and I'm happy to contribute to resolving this issue if there's interest in enabling the feature.

However, I also notice that this fork is based on the [legacy Safe web UI](https://github.com/safe-global/safe-react) which is now deprecated in favor of a [newer Safe web UI](https://github.com/safe-global/web-core) so I'm curious if there's a plan to move over to that as a base for this project as well.

Lastly, I notice that a few of the first-party Safe apps like [Tx Builder](https://github.com/safe-global/safe-react-apps/tree/development/apps/tx-builder) and [Drain Safe](https://github.com/safe-global/safe-react-apps/tree/development/apps/drain-safe) aren't chain specific so it should be relatively easy to make those available so that the app catalogue is a little more useful from the get go and I'm happy to contribute to that effort as well.

**Comment by esantos089** [comment]
Hi @davidsemakula,

Firstly, sorry for my delay and thank you for the compliment, we are pushing this project all together with Moonbeam Team!

We are about to release the new Safe UI and the possibility of interacting with Safe Apps + custom Apps by this next week!

**Comment by davidsemakula** [comment]
Hi @esantos089 
No problem, and great work ... looking forward to the update to the new UI.
I'll close this issue for now.

**Comment by esantos089** [comment]
@davidsemakula ,

The deployment was done! Please, let us know in case of questions or problems!

**Comment by davidsemakula** [comment]
Hi @esantos089
Awesome, Alberto from Moonbeam let me know a while ago that it was up, so I've already had a chance to try it out and looks great.
I'll definitely let you know if I run into any issues 🙂
