### ISSUE TITLE
Smart Contracts compatibility

### ISSUE THREAD

**Issue by datradito** [protofire/moonbeam-safe-react#6]
-Contracts deployment process:

1. How to deploy contracts in new networks
2. Tools to make a deployment

-Review chains to deploy

**Comment by matextrem** [comment]
- Following the steps in the [README](https://github.com/gnosis/safe-contracts/blob/main/README.md) should be very straighfoward to deploy the smart contracts in the desired network (Moonbeam) 
- Hardhat is used in order to deploy the smart contracts
